/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.smaCQA.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.smaCQA.SmaCQAPackage;
import org.xtext.smaCQA.TaxQuestion;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tax Question</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaCQA.impl.TaxQuestionImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.smaCQA.impl.TaxQuestionImpl#getAnswer <em>Answer</em>}</li>
 *   <li>{@link org.xtext.smaCQA.impl.TaxQuestionImpl#getSubSentence <em>Sub Sentence</em>}</li>
 *   <li>{@link org.xtext.smaCQA.impl.TaxQuestionImpl#getAnswerSubSentence <em>Answer Sub Sentence</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TaxQuestionImpl extends MinimalEObjectImpl.Container implements TaxQuestion
{
  /**
	 * The default value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
  protected static final String NAME_EDEFAULT = null;

  /**
	 * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getName()
	 * @generated
	 * @ordered
	 */
  protected String name = NAME_EDEFAULT;

  /**
	 * The default value of the '{@link #getAnswer() <em>Answer</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getAnswer()
	 * @generated
	 * @ordered
	 */
  protected static final String ANSWER_EDEFAULT = null;

  /**
	 * The cached value of the '{@link #getAnswer() <em>Answer</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getAnswer()
	 * @generated
	 * @ordered
	 */
  protected String answer = ANSWER_EDEFAULT;

  /**
	 * The default value of the '{@link #getSubSentence() <em>Sub Sentence</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getSubSentence()
	 * @generated
	 * @ordered
	 */
  protected static final String SUB_SENTENCE_EDEFAULT = null;

  /**
	 * The cached value of the '{@link #getSubSentence() <em>Sub Sentence</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getSubSentence()
	 * @generated
	 * @ordered
	 */
  protected String subSentence = SUB_SENTENCE_EDEFAULT;

  /**
	 * The default value of the '{@link #getAnswerSubSentence() <em>Answer Sub Sentence</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getAnswerSubSentence()
	 * @generated
	 * @ordered
	 */
  protected static final String ANSWER_SUB_SENTENCE_EDEFAULT = null;

  /**
	 * The cached value of the '{@link #getAnswerSubSentence() <em>Answer Sub Sentence</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getAnswerSubSentence()
	 * @generated
	 * @ordered
	 */
  protected String answerSubSentence = ANSWER_SUB_SENTENCE_EDEFAULT;

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected TaxQuestionImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return SmaCQAPackage.Literals.TAX_QUESTION;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public String getName()
  {
		return name;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void setName(String newName)
  {
		String oldName = name;
		name = newName;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, SmaCQAPackage.TAX_QUESTION__NAME, oldName, name));
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public String getAnswer()
  {
		return answer;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void setAnswer(String newAnswer)
  {
		String oldAnswer = answer;
		answer = newAnswer;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, SmaCQAPackage.TAX_QUESTION__ANSWER, oldAnswer, answer));
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public String getSubSentence()
  {
		return subSentence;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void setSubSentence(String newSubSentence)
  {
		String oldSubSentence = subSentence;
		subSentence = newSubSentence;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, SmaCQAPackage.TAX_QUESTION__SUB_SENTENCE, oldSubSentence, subSentence));
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public String getAnswerSubSentence()
  {
		return answerSubSentence;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void setAnswerSubSentence(String newAnswerSubSentence)
  {
		String oldAnswerSubSentence = answerSubSentence;
		answerSubSentence = newAnswerSubSentence;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, SmaCQAPackage.TAX_QUESTION__ANSWER_SUB_SENTENCE, oldAnswerSubSentence, answerSubSentence));
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
		switch (featureID) {
			case SmaCQAPackage.TAX_QUESTION__NAME:
				return getName();
			case SmaCQAPackage.TAX_QUESTION__ANSWER:
				return getAnswer();
			case SmaCQAPackage.TAX_QUESTION__SUB_SENTENCE:
				return getSubSentence();
			case SmaCQAPackage.TAX_QUESTION__ANSWER_SUB_SENTENCE:
				return getAnswerSubSentence();
		}
		return super.eGet(featureID, resolve, coreType);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void eSet(int featureID, Object newValue)
  {
		switch (featureID) {
			case SmaCQAPackage.TAX_QUESTION__NAME:
				setName((String)newValue);
				return;
			case SmaCQAPackage.TAX_QUESTION__ANSWER:
				setAnswer((String)newValue);
				return;
			case SmaCQAPackage.TAX_QUESTION__SUB_SENTENCE:
				setSubSentence((String)newValue);
				return;
			case SmaCQAPackage.TAX_QUESTION__ANSWER_SUB_SENTENCE:
				setAnswerSubSentence((String)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void eUnset(int featureID)
  {
		switch (featureID) {
			case SmaCQAPackage.TAX_QUESTION__NAME:
				setName(NAME_EDEFAULT);
				return;
			case SmaCQAPackage.TAX_QUESTION__ANSWER:
				setAnswer(ANSWER_EDEFAULT);
				return;
			case SmaCQAPackage.TAX_QUESTION__SUB_SENTENCE:
				setSubSentence(SUB_SENTENCE_EDEFAULT);
				return;
			case SmaCQAPackage.TAX_QUESTION__ANSWER_SUB_SENTENCE:
				setAnswerSubSentence(ANSWER_SUB_SENTENCE_EDEFAULT);
				return;
		}
		super.eUnset(featureID);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public boolean eIsSet(int featureID)
  {
		switch (featureID) {
			case SmaCQAPackage.TAX_QUESTION__NAME:
				return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
			case SmaCQAPackage.TAX_QUESTION__ANSWER:
				return ANSWER_EDEFAULT == null ? answer != null : !ANSWER_EDEFAULT.equals(answer);
			case SmaCQAPackage.TAX_QUESTION__SUB_SENTENCE:
				return SUB_SENTENCE_EDEFAULT == null ? subSentence != null : !SUB_SENTENCE_EDEFAULT.equals(subSentence);
			case SmaCQAPackage.TAX_QUESTION__ANSWER_SUB_SENTENCE:
				return ANSWER_SUB_SENTENCE_EDEFAULT == null ? answerSubSentence != null : !ANSWER_SUB_SENTENCE_EDEFAULT.equals(answerSubSentence);
		}
		return super.eIsSet(featureID);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public String toString()
  {
		if (eIsProxy()) return super.toString();

		StringBuilder result = new StringBuilder(super.toString());
		result.append(" (name: ");
		result.append(name);
		result.append(", answer: ");
		result.append(answer);
		result.append(", subSentence: ");
		result.append(subSentence);
		result.append(", answerSubSentence: ");
		result.append(answerSubSentence);
		result.append(')');
		return result.toString();
	}

} //TaxQuestionImpl
