/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.smaCQA.provider;


import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.ResourceLocator;

import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.eclipse.emf.edit.provider.ItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.ItemProviderAdapter;
import org.eclipse.emf.edit.provider.ViewerNotification;

import org.xtext.smaCQA.ShipmentCostResponsibilityQuestion;
import org.xtext.smaCQA.SmaCQAPackage;

/**
 * This is the item provider adapter for a {@link org.xtext.smaCQA.ShipmentCostResponsibilityQuestion} object.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ShipmentCostResponsibilityQuestionItemProvider 
	extends ItemProviderAdapter
	implements
		IEditingDomainItemProvider,
		IStructuredItemContentProvider,
		ITreeItemContentProvider,
		IItemLabelProvider,
		IItemPropertySource {
	/**
	 * This constructs an instance from a factory and a notifier.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ShipmentCostResponsibilityQuestionItemProvider(AdapterFactory adapterFactory) {
		super(adapterFactory);
	}

	/**
	 * This returns the property descriptors for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public List<IItemPropertyDescriptor> getPropertyDescriptors(Object object) {
		if (itemPropertyDescriptors == null) {
			super.getPropertyDescriptors(object);

			addQ1PropertyDescriptor(object);
			addAnswer1PropertyDescriptor(object);
			addQ2PropertyDescriptor(object);
			addAnswer2PropertyDescriptor(object);
			addAnswerUnitCoinFreightRatePropertyDescriptor(object);
			addQ3PropertyDescriptor(object);
			addAnswer3PropertyDescriptor(object);
			addLoadingFeeAnswerUnitCoinPropertyDescriptor(object);
			addQ4PropertyDescriptor(object);
			addAnswer4PropertyDescriptor(object);
			addUnloadingFeeAnswerUnitCoinPropertyDescriptor(object);
			addQ5PropertyDescriptor(object);
			addAnswer5PropertyDescriptor(object);
			addTransportRateAnswerUnitCoinPropertyDescriptor(object);
		}
		return itemPropertyDescriptors;
	}

	/**
	 * This adds a property descriptor for the Q1 feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addQ1PropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_ShipmentCostResponsibilityQuestion_q1_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_ShipmentCostResponsibilityQuestion_q1_feature", "_UI_ShipmentCostResponsibilityQuestion_type"),
				 SmaCQAPackage.Literals.SHIPMENT_COST_RESPONSIBILITY_QUESTION__Q1,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Answer1 feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addAnswer1PropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_ShipmentCostResponsibilityQuestion_answer1_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_ShipmentCostResponsibilityQuestion_answer1_feature", "_UI_ShipmentCostResponsibilityQuestion_type"),
				 SmaCQAPackage.Literals.SHIPMENT_COST_RESPONSIBILITY_QUESTION__ANSWER1,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Q2 feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addQ2PropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_ShipmentCostResponsibilityQuestion_q2_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_ShipmentCostResponsibilityQuestion_q2_feature", "_UI_ShipmentCostResponsibilityQuestion_type"),
				 SmaCQAPackage.Literals.SHIPMENT_COST_RESPONSIBILITY_QUESTION__Q2,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Answer2 feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addAnswer2PropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_ShipmentCostResponsibilityQuestion_answer2_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_ShipmentCostResponsibilityQuestion_answer2_feature", "_UI_ShipmentCostResponsibilityQuestion_type"),
				 SmaCQAPackage.Literals.SHIPMENT_COST_RESPONSIBILITY_QUESTION__ANSWER2,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.INTEGRAL_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Answer Unit Coin Freight Rate feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addAnswerUnitCoinFreightRatePropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_ShipmentCostResponsibilityQuestion_answerUnitCoinFreightRate_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_ShipmentCostResponsibilityQuestion_answerUnitCoinFreightRate_feature", "_UI_ShipmentCostResponsibilityQuestion_type"),
				 SmaCQAPackage.Literals.SHIPMENT_COST_RESPONSIBILITY_QUESTION__ANSWER_UNIT_COIN_FREIGHT_RATE,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Q3 feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addQ3PropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_ShipmentCostResponsibilityQuestion_q3_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_ShipmentCostResponsibilityQuestion_q3_feature", "_UI_ShipmentCostResponsibilityQuestion_type"),
				 SmaCQAPackage.Literals.SHIPMENT_COST_RESPONSIBILITY_QUESTION__Q3,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Answer3 feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addAnswer3PropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_ShipmentCostResponsibilityQuestion_answer3_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_ShipmentCostResponsibilityQuestion_answer3_feature", "_UI_ShipmentCostResponsibilityQuestion_type"),
				 SmaCQAPackage.Literals.SHIPMENT_COST_RESPONSIBILITY_QUESTION__ANSWER3,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.INTEGRAL_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Loading Fee Answer Unit Coin feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addLoadingFeeAnswerUnitCoinPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_ShipmentCostResponsibilityQuestion_loadingFeeAnswerUnitCoin_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_ShipmentCostResponsibilityQuestion_loadingFeeAnswerUnitCoin_feature", "_UI_ShipmentCostResponsibilityQuestion_type"),
				 SmaCQAPackage.Literals.SHIPMENT_COST_RESPONSIBILITY_QUESTION__LOADING_FEE_ANSWER_UNIT_COIN,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Q4 feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addQ4PropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_ShipmentCostResponsibilityQuestion_q4_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_ShipmentCostResponsibilityQuestion_q4_feature", "_UI_ShipmentCostResponsibilityQuestion_type"),
				 SmaCQAPackage.Literals.SHIPMENT_COST_RESPONSIBILITY_QUESTION__Q4,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Answer4 feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addAnswer4PropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_ShipmentCostResponsibilityQuestion_answer4_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_ShipmentCostResponsibilityQuestion_answer4_feature", "_UI_ShipmentCostResponsibilityQuestion_type"),
				 SmaCQAPackage.Literals.SHIPMENT_COST_RESPONSIBILITY_QUESTION__ANSWER4,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.INTEGRAL_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Unloading Fee Answer Unit Coin feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addUnloadingFeeAnswerUnitCoinPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_ShipmentCostResponsibilityQuestion_unloadingFeeAnswerUnitCoin_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_ShipmentCostResponsibilityQuestion_unloadingFeeAnswerUnitCoin_feature", "_UI_ShipmentCostResponsibilityQuestion_type"),
				 SmaCQAPackage.Literals.SHIPMENT_COST_RESPONSIBILITY_QUESTION__UNLOADING_FEE_ANSWER_UNIT_COIN,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Q5 feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addQ5PropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_ShipmentCostResponsibilityQuestion_q5_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_ShipmentCostResponsibilityQuestion_q5_feature", "_UI_ShipmentCostResponsibilityQuestion_type"),
				 SmaCQAPackage.Literals.SHIPMENT_COST_RESPONSIBILITY_QUESTION__Q5,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Answer5 feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addAnswer5PropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_ShipmentCostResponsibilityQuestion_answer5_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_ShipmentCostResponsibilityQuestion_answer5_feature", "_UI_ShipmentCostResponsibilityQuestion_type"),
				 SmaCQAPackage.Literals.SHIPMENT_COST_RESPONSIBILITY_QUESTION__ANSWER5,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.INTEGRAL_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This adds a property descriptor for the Transport Rate Answer Unit Coin feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addTransportRateAnswerUnitCoinPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_ShipmentCostResponsibilityQuestion_transportRateAnswerUnitCoin_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_ShipmentCostResponsibilityQuestion_transportRateAnswerUnitCoin_feature", "_UI_ShipmentCostResponsibilityQuestion_type"),
				 SmaCQAPackage.Literals.SHIPMENT_COST_RESPONSIBILITY_QUESTION__TRANSPORT_RATE_ANSWER_UNIT_COIN,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This returns ShipmentCostResponsibilityQuestion.gif.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object getImage(Object object) {
		return overlayImage(object, getResourceLocator().getImage("full/obj16/ShipmentCostResponsibilityQuestion"));
	}

	/**
	 * This returns the label text for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getText(Object object) {
		String label = ((ShipmentCostResponsibilityQuestion)object).getQ1();
		return label == null || label.length() == 0 ?
			getString("_UI_ShipmentCostResponsibilityQuestion_type") :
			getString("_UI_ShipmentCostResponsibilityQuestion_type") + " " + label;
	}


	/**
	 * This handles model notifications by calling {@link #updateChildren} to update any cached
	 * children and by creating a viewer notification, which it passes to {@link #fireNotifyChanged}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void notifyChanged(Notification notification) {
		updateChildren(notification);

		switch (notification.getFeatureID(ShipmentCostResponsibilityQuestion.class)) {
			case SmaCQAPackage.SHIPMENT_COST_RESPONSIBILITY_QUESTION__Q1:
			case SmaCQAPackage.SHIPMENT_COST_RESPONSIBILITY_QUESTION__ANSWER1:
			case SmaCQAPackage.SHIPMENT_COST_RESPONSIBILITY_QUESTION__Q2:
			case SmaCQAPackage.SHIPMENT_COST_RESPONSIBILITY_QUESTION__ANSWER2:
			case SmaCQAPackage.SHIPMENT_COST_RESPONSIBILITY_QUESTION__ANSWER_UNIT_COIN_FREIGHT_RATE:
			case SmaCQAPackage.SHIPMENT_COST_RESPONSIBILITY_QUESTION__Q3:
			case SmaCQAPackage.SHIPMENT_COST_RESPONSIBILITY_QUESTION__ANSWER3:
			case SmaCQAPackage.SHIPMENT_COST_RESPONSIBILITY_QUESTION__LOADING_FEE_ANSWER_UNIT_COIN:
			case SmaCQAPackage.SHIPMENT_COST_RESPONSIBILITY_QUESTION__Q4:
			case SmaCQAPackage.SHIPMENT_COST_RESPONSIBILITY_QUESTION__ANSWER4:
			case SmaCQAPackage.SHIPMENT_COST_RESPONSIBILITY_QUESTION__UNLOADING_FEE_ANSWER_UNIT_COIN:
			case SmaCQAPackage.SHIPMENT_COST_RESPONSIBILITY_QUESTION__Q5:
			case SmaCQAPackage.SHIPMENT_COST_RESPONSIBILITY_QUESTION__ANSWER5:
			case SmaCQAPackage.SHIPMENT_COST_RESPONSIBILITY_QUESTION__TRANSPORT_RATE_ANSWER_UNIT_COIN:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), false, true));
				return;
		}
		super.notifyChanged(notification);
	}

	/**
	 * This adds {@link org.eclipse.emf.edit.command.CommandParameter}s describing the children
	 * that can be created under this object.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
		super.collectNewChildDescriptors(newChildDescriptors, object);
	}

	/**
	 * Return the resource locator for this item provider's resources.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ResourceLocator getResourceLocator() {
		return SmaCQAEditPlugin.INSTANCE;
	}

}
