/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.smaCQA;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Shipment Question</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getShipmentDetails <em>Shipment Details</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getSanitaryControl <em>Sanitary Control</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getCustoms <em>Customs</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getImportTax <em>Import Tax</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getGeographicalQuestion <em>Geographical Question</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getAddressPickup <em>Address Pickup</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getAddressDelivery <em>Address Delivery</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getShipmentTrackingNumber <em>Shipment Tracking Number</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getDangerousLoad <em>Dangerous Load</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getPerishable <em>Perishable</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getCargoType <em>Cargo Type</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getCargoWeight <em>Cargo Weight</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getCargoDimensions <em>Cargo Dimensions</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getSeaShipment <em>Sea Shipment</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getMeans <em>Means</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getCompany <em>Company</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getDeliveryDeadline <em>Delivery Deadline</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getUpdatesAndMonitoring <em>Updates And Monitoring</em>}</li>
 *   <li>{@link org.xtext.smaCQA.ShipmentQuestion#getExternalMediator <em>External Mediator</em>}</li>
 * </ul>
 *
 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion()
 * @model
 * @generated
 */
public interface ShipmentQuestion extends EObject
{
  /**
	 * Returns the value of the '<em><b>Shipment Details</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Shipment Details</em>' containment reference.
	 * @see #setShipmentDetails(ShipmentDetailsQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_ShipmentDetails()
	 * @model containment="true"
	 * @generated
	 */
  ShipmentDetailsQuestion getShipmentDetails();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getShipmentDetails <em>Shipment Details</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Shipment Details</em>' containment reference.
	 * @see #getShipmentDetails()
	 * @generated
	 */
  void setShipmentDetails(ShipmentDetailsQuestion value);

  /**
	 * Returns the value of the '<em><b>Sanitary Control</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Sanitary Control</em>' containment reference.
	 * @see #setSanitaryControl(SanitaryControlQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_SanitaryControl()
	 * @model containment="true"
	 * @generated
	 */
  SanitaryControlQuestion getSanitaryControl();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getSanitaryControl <em>Sanitary Control</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Sanitary Control</em>' containment reference.
	 * @see #getSanitaryControl()
	 * @generated
	 */
  void setSanitaryControl(SanitaryControlQuestion value);

  /**
	 * Returns the value of the '<em><b>Customs</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Customs</em>' containment reference.
	 * @see #setCustoms(CustomsQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_Customs()
	 * @model containment="true"
	 * @generated
	 */
  CustomsQuestion getCustoms();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getCustoms <em>Customs</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Customs</em>' containment reference.
	 * @see #getCustoms()
	 * @generated
	 */
  void setCustoms(CustomsQuestion value);

  /**
	 * Returns the value of the '<em><b>Import Tax</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Import Tax</em>' containment reference.
	 * @see #setImportTax(ImportTaxQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_ImportTax()
	 * @model containment="true"
	 * @generated
	 */
  ImportTaxQuestion getImportTax();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getImportTax <em>Import Tax</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Import Tax</em>' containment reference.
	 * @see #getImportTax()
	 * @generated
	 */
  void setImportTax(ImportTaxQuestion value);

  /**
	 * Returns the value of the '<em><b>Geographical Question</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Geographical Question</em>' containment reference.
	 * @see #setGeographicalQuestion(GeographicalQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_GeographicalQuestion()
	 * @model containment="true"
	 * @generated
	 */
  GeographicalQuestion getGeographicalQuestion();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getGeographicalQuestion <em>Geographical Question</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Geographical Question</em>' containment reference.
	 * @see #getGeographicalQuestion()
	 * @generated
	 */
  void setGeographicalQuestion(GeographicalQuestion value);

  /**
	 * Returns the value of the '<em><b>Address Pickup</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Address Pickup</em>' containment reference.
	 * @see #setAddressPickup(AddressPickupQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_AddressPickup()
	 * @model containment="true"
	 * @generated
	 */
  AddressPickupQuestion getAddressPickup();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getAddressPickup <em>Address Pickup</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Address Pickup</em>' containment reference.
	 * @see #getAddressPickup()
	 * @generated
	 */
  void setAddressPickup(AddressPickupQuestion value);

  /**
	 * Returns the value of the '<em><b>Address Delivery</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Address Delivery</em>' containment reference.
	 * @see #setAddressDelivery(AddressDeliveryQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_AddressDelivery()
	 * @model containment="true"
	 * @generated
	 */
  AddressDeliveryQuestion getAddressDelivery();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getAddressDelivery <em>Address Delivery</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Address Delivery</em>' containment reference.
	 * @see #getAddressDelivery()
	 * @generated
	 */
  void setAddressDelivery(AddressDeliveryQuestion value);

  /**
	 * Returns the value of the '<em><b>Shipment Tracking Number</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Shipment Tracking Number</em>' containment reference.
	 * @see #setShipmentTrackingNumber(ShipmentTrackingNumberQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_ShipmentTrackingNumber()
	 * @model containment="true"
	 * @generated
	 */
  ShipmentTrackingNumberQuestion getShipmentTrackingNumber();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getShipmentTrackingNumber <em>Shipment Tracking Number</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Shipment Tracking Number</em>' containment reference.
	 * @see #getShipmentTrackingNumber()
	 * @generated
	 */
  void setShipmentTrackingNumber(ShipmentTrackingNumberQuestion value);

  /**
	 * Returns the value of the '<em><b>Dangerous Load</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Dangerous Load</em>' containment reference.
	 * @see #setDangerousLoad(DangerousLoadQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_DangerousLoad()
	 * @model containment="true"
	 * @generated
	 */
  DangerousLoadQuestion getDangerousLoad();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getDangerousLoad <em>Dangerous Load</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Dangerous Load</em>' containment reference.
	 * @see #getDangerousLoad()
	 * @generated
	 */
  void setDangerousLoad(DangerousLoadQuestion value);

  /**
	 * Returns the value of the '<em><b>Perishable</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Perishable</em>' containment reference.
	 * @see #setPerishable(PerishableQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_Perishable()
	 * @model containment="true"
	 * @generated
	 */
  PerishableQuestion getPerishable();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getPerishable <em>Perishable</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Perishable</em>' containment reference.
	 * @see #getPerishable()
	 * @generated
	 */
  void setPerishable(PerishableQuestion value);

  /**
	 * Returns the value of the '<em><b>Cargo Type</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Cargo Type</em>' containment reference.
	 * @see #setCargoType(CargoTypeQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_CargoType()
	 * @model containment="true"
	 * @generated
	 */
  CargoTypeQuestion getCargoType();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getCargoType <em>Cargo Type</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Cargo Type</em>' containment reference.
	 * @see #getCargoType()
	 * @generated
	 */
  void setCargoType(CargoTypeQuestion value);

  /**
	 * Returns the value of the '<em><b>Cargo Weight</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Cargo Weight</em>' containment reference.
	 * @see #setCargoWeight(CargoWeightQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_CargoWeight()
	 * @model containment="true"
	 * @generated
	 */
  CargoWeightQuestion getCargoWeight();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getCargoWeight <em>Cargo Weight</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Cargo Weight</em>' containment reference.
	 * @see #getCargoWeight()
	 * @generated
	 */
  void setCargoWeight(CargoWeightQuestion value);

  /**
	 * Returns the value of the '<em><b>Cargo Dimensions</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Cargo Dimensions</em>' containment reference.
	 * @see #setCargoDimensions(CargoDimensionsQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_CargoDimensions()
	 * @model containment="true"
	 * @generated
	 */
  CargoDimensionsQuestion getCargoDimensions();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getCargoDimensions <em>Cargo Dimensions</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Cargo Dimensions</em>' containment reference.
	 * @see #getCargoDimensions()
	 * @generated
	 */
  void setCargoDimensions(CargoDimensionsQuestion value);

  /**
	 * Returns the value of the '<em><b>Sea Shipment</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Sea Shipment</em>' containment reference.
	 * @see #setSeaShipment(SeaShipmentQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_SeaShipment()
	 * @model containment="true"
	 * @generated
	 */
  SeaShipmentQuestion getSeaShipment();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getSeaShipment <em>Sea Shipment</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Sea Shipment</em>' containment reference.
	 * @see #getSeaShipment()
	 * @generated
	 */
  void setSeaShipment(SeaShipmentQuestion value);

  /**
	 * Returns the value of the '<em><b>Means</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Means</em>' containment reference.
	 * @see #setMeans(MeansTransportQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_Means()
	 * @model containment="true"
	 * @generated
	 */
  MeansTransportQuestion getMeans();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getMeans <em>Means</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Means</em>' containment reference.
	 * @see #getMeans()
	 * @generated
	 */
  void setMeans(MeansTransportQuestion value);

  /**
	 * Returns the value of the '<em><b>Company</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Company</em>' containment reference.
	 * @see #setCompany(CompanyQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_Company()
	 * @model containment="true"
	 * @generated
	 */
  CompanyQuestion getCompany();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getCompany <em>Company</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Company</em>' containment reference.
	 * @see #getCompany()
	 * @generated
	 */
  void setCompany(CompanyQuestion value);

  /**
	 * Returns the value of the '<em><b>Delivery Deadline</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Delivery Deadline</em>' containment reference.
	 * @see #setDeliveryDeadline(DeliveryDeadlineQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_DeliveryDeadline()
	 * @model containment="true"
	 * @generated
	 */
  DeliveryDeadlineQuestion getDeliveryDeadline();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getDeliveryDeadline <em>Delivery Deadline</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Delivery Deadline</em>' containment reference.
	 * @see #getDeliveryDeadline()
	 * @generated
	 */
  void setDeliveryDeadline(DeliveryDeadlineQuestion value);

  /**
	 * Returns the value of the '<em><b>Updates And Monitoring</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Updates And Monitoring</em>' containment reference.
	 * @see #setUpdatesAndMonitoring(UpdatesAndMonitoringQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_UpdatesAndMonitoring()
	 * @model containment="true"
	 * @generated
	 */
  UpdatesAndMonitoringQuestion getUpdatesAndMonitoring();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getUpdatesAndMonitoring <em>Updates And Monitoring</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Updates And Monitoring</em>' containment reference.
	 * @see #getUpdatesAndMonitoring()
	 * @generated
	 */
  void setUpdatesAndMonitoring(UpdatesAndMonitoringQuestion value);

  /**
	 * Returns the value of the '<em><b>External Mediator</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>External Mediator</em>' containment reference.
	 * @see #setExternalMediator(ExternalMediatorQuestion)
	 * @see org.xtext.smaCQA.SmaCQAPackage#getShipmentQuestion_ExternalMediator()
	 * @model containment="true"
	 * @generated
	 */
  ExternalMediatorQuestion getExternalMediator();

  /**
	 * Sets the value of the '{@link org.xtext.smaCQA.ShipmentQuestion#getExternalMediator <em>External Mediator</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>External Mediator</em>' containment reference.
	 * @see #getExternalMediator()
	 * @generated
	 */
  void setExternalMediator(ExternalMediatorQuestion value);

} // ShipmentQuestion
