/*
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.ide.contentassist.antlr.internal.InternalSmaCQAParser;
import org.xtext.services.SmaCQAGrammarAccess;

public class SmaCQAParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(SmaCQAGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, SmaCQAGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getValueObjectQuestionAccess().getAlternatives(), "rule__ValueObjectQuestion__Alternatives");
			builder.put(grammarAccess.getValueObjectRightQuestionAccess().getAnswerAlternatives_2_0(), "rule__ValueObjectRightQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getTokenAccess().getAlternatives(), "rule__Token__Alternatives");
			builder.put(grammarAccess.getTokenERC20Access().getAnswerMintSentenceAlternatives_11_0(), "rule__TokenERC20__AnswerMintSentenceAlternatives_11_0");
			builder.put(grammarAccess.getTokenERC20Access().getAnswerBurnSentenceAlternatives_14_0(), "rule__TokenERC20__AnswerBurnSentenceAlternatives_14_0");
			builder.put(grammarAccess.getTokenERC223Access().getAnswerMintSentenceAlternatives_11_0(), "rule__TokenERC223__AnswerMintSentenceAlternatives_11_0");
			builder.put(grammarAccess.getTokenERC223Access().getAnswerBurnSentenceAlternatives_14_0(), "rule__TokenERC223__AnswerBurnSentenceAlternatives_14_0");
			builder.put(grammarAccess.getTokenERC721Access().getAnswerMintSentenceAlternatives_7_0(), "rule__TokenERC721__AnswerMintSentenceAlternatives_7_0");
			builder.put(grammarAccess.getTokenERC721Access().getAnswerBurnSentenceAlternatives_10_0(), "rule__TokenERC721__AnswerBurnSentenceAlternatives_10_0");
			builder.put(grammarAccess.getTokenERC721Access().getAnswerMetadataSentenceAlternatives_17_0(), "rule__TokenERC721__AnswerMetadataSentenceAlternatives_17_0");
			builder.put(grammarAccess.getRepeatValueExchangeQuestionAccess().getAnswerAlternatives_2_0(), "rule__RepeatValueExchangeQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getConditionsValueExchangeQuestionAccess().getAnswerAlternatives_2_0(), "rule__ConditionsValueExchangeQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getAdditionalLegalDocumentQuestionAccess().getAnswerAlternatives_2_0(), "rule__AdditionalLegalDocumentQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getShipmentDetailsQuestionAccess().getAnswerAlternatives_2_0(), "rule__ShipmentDetailsQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getSanitaryControlQuestionAccess().getAnswerAlternatives_2_0(), "rule__SanitaryControlQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getCustomsQuestionAccess().getAnswerAlternatives_2_0(), "rule__CustomsQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getImportTaxQuestionAccess().getAnswerAlternatives_2_0(), "rule__ImportTaxQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getGeographicalQuestionAccess().getAnswerAlternatives_2_0(), "rule__GeographicalQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getDangerousLoadQuestionAccess().getAnswerAlternatives_2_0(), "rule__DangerousLoadQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getPerishableQuestionAccess().getAnswerAlternatives_2_0(), "rule__PerishableQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getSeaShipmentQuestionAccess().getAnswerAlternatives_2_0(), "rule__SeaShipmentQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getMaritimeQuestionAccess().getAnswer3Alternatives_6_2_0(), "rule__MaritimeQuestion__Answer3Alternatives_6_2_0");
			builder.put(grammarAccess.getExternalMediatorQuestionAccess().getAnswerAlternatives_2_0(), "rule__ExternalMediatorQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getShipmentInsuranceQuestionAccess().getAnswerAlternatives_2_0(), "rule__ShipmentInsuranceQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getReturnsOrCancellationsQuestionAccess().getAnswerAlternatives_2_0(), "rule__ReturnsOrCancellationsQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getInternationalSealQuestionAccess().getAnswerAlternatives_2_0(), "rule__InternationalSealQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getHealthInspectionQuestionAccess().getAnswerAlternatives_2_0(), "rule__HealthInspectionQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getStorageConditionsQuestionAccess().getAnswerAlternatives_2_0(), "rule__StorageConditionsQuestion__AnswerAlternatives_2_0");
			builder.put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
			builder.put(grammarAccess.getUnitTimeAccess().getAlternatives(), "rule__UnitTime__Alternatives");
			builder.put(grammarAccess.getUnitCoinAccess().getAlternatives(), "rule__UnitCoin__Alternatives");
			builder.put(grammarAccess.getVoyagetypeAccess().getAlternatives(), "rule__Voyagetype__Alternatives");
			builder.put(grammarAccess.getInspectionResultAccess().getAlternatives(), "rule__InspectionResult__Alternatives");
			builder.put(grammarAccess.getParticipantsAccess().getAlternatives(), "rule__Participants__Alternatives");
			builder.put(grammarAccess.getValueExchangeAccess().getGroup(), "rule__ValueExchange__Group__0");
			builder.put(grammarAccess.getValueExchangeAccess().getGroup_8(), "rule__ValueExchange__Group_8__0");
			builder.put(grammarAccess.getValueExchangeAccess().getGroup_9(), "rule__ValueExchange__Group_9__0");
			builder.put(grammarAccess.getValueExchangeAccess().getGroup_10(), "rule__ValueExchange__Group_10__0");
			builder.put(grammarAccess.getValueExchangeAccess().getGroup_11(), "rule__ValueExchange__Group_11__0");
			builder.put(grammarAccess.getValueExchangeAccess().getGroup_12(), "rule__ValueExchange__Group_12__0");
			builder.put(grammarAccess.getValueExchangeAccess().getGroup_13(), "rule__ValueExchange__Group_13__0");
			builder.put(grammarAccess.getDataQuestionAccess().getGroup(), "rule__DataQuestion__Group__0");
			builder.put(grammarAccess.getShipmentQuestionAccess().getGroup(), "rule__ShipmentQuestion__Group__0");
			builder.put(grammarAccess.getInsuranceQuestionAccess().getGroup(), "rule__InsuranceQuestion__Group__0");
			builder.put(grammarAccess.getAlimentaryQuestionAccess().getGroup(), "rule__AlimentaryQuestion__Group__0");
			builder.put(grammarAccess.getValueObjectRightQuestionAccess().getGroup(), "rule__ValueObjectRightQuestion__Group__0");
			builder.put(grammarAccess.getValueObjectTokenQuestionAccess().getGroup(), "rule__ValueObjectTokenQuestion__Group__0");
			builder.put(grammarAccess.getValueObjectTangibleQuestionAccess().getGroup(), "rule__ValueObjectTangibleQuestion__Group__0");
			builder.put(grammarAccess.getDataRegisterAccess().getGroup(), "rule__DataRegister__Group__0");
			builder.put(grammarAccess.getTokenERC20Access().getGroup(), "rule__TokenERC20__Group__0");
			builder.put(grammarAccess.getTokenERC223Access().getGroup(), "rule__TokenERC223__Group__0");
			builder.put(grammarAccess.getTokenERC721Access().getGroup(), "rule__TokenERC721__Group__0");
			builder.put(grammarAccess.getTokenERC721Access().getGroup_18(), "rule__TokenERC721__Group_18__0");
			builder.put(grammarAccess.getTokenERC721Access().getGroup_19(), "rule__TokenERC721__Group_19__0");
			builder.put(grammarAccess.getTimeValueExchangeDurationQuestionAccess().getGroup(), "rule__TimeValueExchangeDurationQuestion__Group__0");
			builder.put(grammarAccess.getTimeStartValueExchangeQuestionAccess().getGroup(), "rule__TimeStartValueExchangeQuestion__Group__0");
			builder.put(grammarAccess.getRepeatValueExchangeQuestionAccess().getGroup(), "rule__RepeatValueExchangeQuestion__Group__0");
			builder.put(grammarAccess.getConditionsValueExchangeQuestionAccess().getGroup(), "rule__ConditionsValueExchangeQuestion__Group__0");
			builder.put(grammarAccess.getLegalQuestionAccess().getGroup(), "rule__LegalQuestion__Group__0");
			builder.put(grammarAccess.getAgeQuestionAccess().getGroup(), "rule__AgeQuestion__Group__0");
			builder.put(grammarAccess.getTaxQuestionAccess().getGroup(), "rule__TaxQuestion__Group__0");
			builder.put(grammarAccess.getAdditionalLegalDocumentQuestionAccess().getGroup(), "rule__AdditionalLegalDocumentQuestion__Group__0");
			builder.put(grammarAccess.getRegulatoryComplianceQuestionAccess().getGroup(), "rule__RegulatoryComplianceQuestion__Group__0");
			builder.put(grammarAccess.getEconomyQuestionAccess().getGroup(), "rule__EconomyQuestion__Group__0");
			builder.put(grammarAccess.getMinimumAmountQuestionAccess().getGroup(), "rule__MinimumAmountQuestion__Group__0");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getGroup(), "rule__ShipmentCostResponsibilityQuestion__Group__0");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getGroup_3(), "rule__ShipmentCostResponsibilityQuestion__Group_3__0");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getGroup_4(), "rule__ShipmentCostResponsibilityQuestion__Group_4__0");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getGroup_5(), "rule__ShipmentCostResponsibilityQuestion__Group_5__0");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getGroup_6(), "rule__ShipmentCostResponsibilityQuestion__Group_6__0");
			builder.put(grammarAccess.getShipmentDetailsQuestionAccess().getGroup(), "rule__ShipmentDetailsQuestion__Group__0");
			builder.put(grammarAccess.getSanitaryControlQuestionAccess().getGroup(), "rule__SanitaryControlQuestion__Group__0");
			builder.put(grammarAccess.getCustomsQuestionAccess().getGroup(), "rule__CustomsQuestion__Group__0");
			builder.put(grammarAccess.getImportTaxQuestionAccess().getGroup(), "rule__ImportTaxQuestion__Group__0");
			builder.put(grammarAccess.getTaxShipmentDetailsQuestionAccess().getGroup(), "rule__TaxShipmentDetailsQuestion__Group__0");
			builder.put(grammarAccess.getGeographicalQuestionAccess().getGroup(), "rule__GeographicalQuestion__Group__0");
			builder.put(grammarAccess.getGeographicalRestrictionQuestionAccess().getGroup(), "rule__GeographicalRestrictionQuestion__Group__0");
			builder.put(grammarAccess.getAddressPickupQuestionAccess().getGroup(), "rule__AddressPickupQuestion__Group__0");
			builder.put(grammarAccess.getAddressDeliveryQuestionAccess().getGroup(), "rule__AddressDeliveryQuestion__Group__0");
			builder.put(grammarAccess.getShipmentTrackingNumberQuestionAccess().getGroup(), "rule__ShipmentTrackingNumberQuestion__Group__0");
			builder.put(grammarAccess.getDangerousLoadQuestionAccess().getGroup(), "rule__DangerousLoadQuestion__Group__0");
			builder.put(grammarAccess.getSpecialMeasuresQuestionAccess().getGroup(), "rule__SpecialMeasuresQuestion__Group__0");
			builder.put(grammarAccess.getPerishableQuestionAccess().getGroup(), "rule__PerishableQuestion__Group__0");
			builder.put(grammarAccess.getExpirationDateQuestionAccess().getGroup(), "rule__ExpirationDateQuestion__Group__0");
			builder.put(grammarAccess.getCargoTypeQuestionAccess().getGroup(), "rule__CargoTypeQuestion__Group__0");
			builder.put(grammarAccess.getCargoWeightQuestionAccess().getGroup(), "rule__CargoWeightQuestion__Group__0");
			builder.put(grammarAccess.getCargoDimensionsQuestionAccess().getGroup(), "rule__CargoDimensionsQuestion__Group__0");
			builder.put(grammarAccess.getSeaShipmentQuestionAccess().getGroup(), "rule__SeaShipmentQuestion__Group__0");
			builder.put(grammarAccess.getMaritimeQuestionAccess().getGroup(), "rule__MaritimeQuestion__Group__0");
			builder.put(grammarAccess.getMaritimeQuestionAccess().getGroup_6(), "rule__MaritimeQuestion__Group_6__0");
			builder.put(grammarAccess.getVoyageQuestionAccess().getGroup(), "rule__VoyageQuestion__Group__0");
			builder.put(grammarAccess.getMeansTransportQuestionAccess().getGroup(), "rule__MeansTransportQuestion__Group__0");
			builder.put(grammarAccess.getCompanyQuestionAccess().getGroup(), "rule__CompanyQuestion__Group__0");
			builder.put(grammarAccess.getDeliveryDeadlineQuestionAccess().getGroup(), "rule__DeliveryDeadlineQuestion__Group__0");
			builder.put(grammarAccess.getUpdatesAndMonitoringQuestionAccess().getGroup(), "rule__UpdatesAndMonitoringQuestion__Group__0");
			builder.put(grammarAccess.getExternalMediatorQuestionAccess().getGroup(), "rule__ExternalMediatorQuestion__Group__0");
			builder.put(grammarAccess.getMediatorNameQuestionAccess().getGroup(), "rule__MediatorNameQuestion__Group__0");
			builder.put(grammarAccess.getShipmentInsuranceQuestionAccess().getGroup(), "rule__ShipmentInsuranceQuestion__Group__0");
			builder.put(grammarAccess.getInsuranceDetailsQuestionAccess().getGroup(), "rule__InsuranceDetailsQuestion__Group__0");
			builder.put(grammarAccess.getInsuranceDetailsQuestionAccess().getGroup_0(), "rule__InsuranceDetailsQuestion__Group_0__0");
			builder.put(grammarAccess.getInsuranceDetailsQuestionAccess().getGroup_1(), "rule__InsuranceDetailsQuestion__Group_1__0");
			builder.put(grammarAccess.getInsuranceDetailsQuestionAccess().getGroup_2(), "rule__InsuranceDetailsQuestion__Group_2__0");
			builder.put(grammarAccess.getReturnsOrCancellationsQuestionAccess().getGroup(), "rule__ReturnsOrCancellationsQuestion__Group__0");
			builder.put(grammarAccess.getReturnsManagementQuestionAccess().getGroup(), "rule__ReturnsManagementQuestion__Group__0");
			builder.put(grammarAccess.getPenaltyForNeglectQuestionAccess().getGroup(), "rule__PenaltyForNeglectQuestion__Group__0");
			builder.put(grammarAccess.getAgreedPriceQuestionAccess().getGroup(), "rule__AgreedPriceQuestion__Group__0");
			builder.put(grammarAccess.getProductQualityQuestionAccess().getGroup(), "rule__ProductQualityQuestion__Group__0");
			builder.put(grammarAccess.getExpectedQualityQuestionAccess().getGroup(), "rule__ExpectedQualityQuestion__Group__0");
			builder.put(grammarAccess.getInternationalSealQuestionAccess().getGroup(), "rule__InternationalSealQuestion__Group__0");
			builder.put(grammarAccess.getInternacionalSealNameQuestionAccess().getGroup(), "rule__InternacionalSealNameQuestion__Group__0");
			builder.put(grammarAccess.getHealthInspectionQuestionAccess().getGroup(), "rule__HealthInspectionQuestion__Group__0");
			builder.put(grammarAccess.getInspectionResultQuestionAccess().getGroup(), "rule__InspectionResultQuestion__Group__0");
			builder.put(grammarAccess.getStorageConditionsQuestionAccess().getGroup(), "rule__StorageConditionsQuestion__Group__0");
			builder.put(grammarAccess.getModelAccess().getValueExchangesAssignment(), "rule__Model__ValueExchangesAssignment");
			builder.put(grammarAccess.getValueExchangeAccess().getActorSendAssignment_1(), "rule__ValueExchange__ActorSendAssignment_1");
			builder.put(grammarAccess.getValueExchangeAccess().getActorReceiptAssignment_3(), "rule__ValueExchange__ActorReceiptAssignment_3");
			builder.put(grammarAccess.getValueExchangeAccess().getValueObjectAssignment_5(), "rule__ValueExchange__ValueObjectAssignment_5");
			builder.put(grammarAccess.getValueExchangeAccess().getDataQuestionAssignment_8_2(), "rule__ValueExchange__DataQuestionAssignment_8_2");
			builder.put(grammarAccess.getValueExchangeAccess().getLegalQuestionAssignment_9_2(), "rule__ValueExchange__LegalQuestionAssignment_9_2");
			builder.put(grammarAccess.getValueExchangeAccess().getEconomyQuestionAssignment_10_2(), "rule__ValueExchange__EconomyQuestionAssignment_10_2");
			builder.put(grammarAccess.getValueExchangeAccess().getShipmentQuestionAssignment_11_2(), "rule__ValueExchange__ShipmentQuestionAssignment_11_2");
			builder.put(grammarAccess.getValueExchangeAccess().getInsuranceQuestionAssignment_12_2(), "rule__ValueExchange__InsuranceQuestionAssignment_12_2");
			builder.put(grammarAccess.getValueExchangeAccess().getAlimentaryQuestionAssignment_13_2(), "rule__ValueExchange__AlimentaryQuestionAssignment_13_2");
			builder.put(grammarAccess.getDataQuestionAccess().getTimeDurationValueExchangeAssignment_0(), "rule__DataQuestion__TimeDurationValueExchangeAssignment_0");
			builder.put(grammarAccess.getDataQuestionAccess().getTimeStartValueExchangeAssignment_1(), "rule__DataQuestion__TimeStartValueExchangeAssignment_1");
			builder.put(grammarAccess.getDataQuestionAccess().getRepeatValueExchangeAssignment_2(), "rule__DataQuestion__RepeatValueExchangeAssignment_2");
			builder.put(grammarAccess.getDataQuestionAccess().getConditionValueExchangeAssignment_3(), "rule__DataQuestion__ConditionValueExchangeAssignment_3");
			builder.put(grammarAccess.getDataQuestionAccess().getValueObjectTypeValueExchangeAssignment_4(), "rule__DataQuestion__ValueObjectTypeValueExchangeAssignment_4");
			builder.put(grammarAccess.getShipmentQuestionAccess().getShipmentDetailsAssignment_0(), "rule__ShipmentQuestion__ShipmentDetailsAssignment_0");
			builder.put(grammarAccess.getShipmentQuestionAccess().getSanitaryControlAssignment_1(), "rule__ShipmentQuestion__SanitaryControlAssignment_1");
			builder.put(grammarAccess.getShipmentQuestionAccess().getCustomsAssignment_2(), "rule__ShipmentQuestion__CustomsAssignment_2");
			builder.put(grammarAccess.getShipmentQuestionAccess().getImportTaxAssignment_3(), "rule__ShipmentQuestion__ImportTaxAssignment_3");
			builder.put(grammarAccess.getShipmentQuestionAccess().getGeographicalQuestionAssignment_4(), "rule__ShipmentQuestion__GeographicalQuestionAssignment_4");
			builder.put(grammarAccess.getShipmentQuestionAccess().getAddressPickupAssignment_5(), "rule__ShipmentQuestion__AddressPickupAssignment_5");
			builder.put(grammarAccess.getShipmentQuestionAccess().getAddressDeliveryAssignment_6(), "rule__ShipmentQuestion__AddressDeliveryAssignment_6");
			builder.put(grammarAccess.getShipmentQuestionAccess().getShipmentTrackingNumberAssignment_7(), "rule__ShipmentQuestion__ShipmentTrackingNumberAssignment_7");
			builder.put(grammarAccess.getShipmentQuestionAccess().getDangerousLoadAssignment_8(), "rule__ShipmentQuestion__DangerousLoadAssignment_8");
			builder.put(grammarAccess.getShipmentQuestionAccess().getPerishableAssignment_9(), "rule__ShipmentQuestion__PerishableAssignment_9");
			builder.put(grammarAccess.getShipmentQuestionAccess().getCargoTypeAssignment_10(), "rule__ShipmentQuestion__CargoTypeAssignment_10");
			builder.put(grammarAccess.getShipmentQuestionAccess().getCargoWeightAssignment_11(), "rule__ShipmentQuestion__CargoWeightAssignment_11");
			builder.put(grammarAccess.getShipmentQuestionAccess().getCargoDimensionsAssignment_12(), "rule__ShipmentQuestion__CargoDimensionsAssignment_12");
			builder.put(grammarAccess.getShipmentQuestionAccess().getSeaShipmentAssignment_13(), "rule__ShipmentQuestion__SeaShipmentAssignment_13");
			builder.put(grammarAccess.getShipmentQuestionAccess().getMeansAssignment_14(), "rule__ShipmentQuestion__MeansAssignment_14");
			builder.put(grammarAccess.getShipmentQuestionAccess().getCompanyAssignment_15(), "rule__ShipmentQuestion__CompanyAssignment_15");
			builder.put(grammarAccess.getShipmentQuestionAccess().getDeliveryDeadlineAssignment_16(), "rule__ShipmentQuestion__DeliveryDeadlineAssignment_16");
			builder.put(grammarAccess.getShipmentQuestionAccess().getUpdatesAndMonitoringAssignment_17(), "rule__ShipmentQuestion__UpdatesAndMonitoringAssignment_17");
			builder.put(grammarAccess.getShipmentQuestionAccess().getExternalMediatorAssignment_18(), "rule__ShipmentQuestion__ExternalMediatorAssignment_18");
			builder.put(grammarAccess.getInsuranceQuestionAccess().getShipmentInsuranceAssignment_0(), "rule__InsuranceQuestion__ShipmentInsuranceAssignment_0");
			builder.put(grammarAccess.getInsuranceQuestionAccess().getInsuranceDetailsAssignment_1(), "rule__InsuranceQuestion__InsuranceDetailsAssignment_1");
			builder.put(grammarAccess.getInsuranceQuestionAccess().getReturnsOrCancellationsAssignment_2(), "rule__InsuranceQuestion__ReturnsOrCancellationsAssignment_2");
			builder.put(grammarAccess.getInsuranceQuestionAccess().getPenaltyForNeglectAssignment_3(), "rule__InsuranceQuestion__PenaltyForNeglectAssignment_3");
			builder.put(grammarAccess.getAlimentaryQuestionAccess().getAgreedPriceAssignment_0(), "rule__AlimentaryQuestion__AgreedPriceAssignment_0");
			builder.put(grammarAccess.getAlimentaryQuestionAccess().getProductQualityAssignment_1(), "rule__AlimentaryQuestion__ProductQualityAssignment_1");
			builder.put(grammarAccess.getAlimentaryQuestionAccess().getInternationalSealAssignment_2(), "rule__AlimentaryQuestion__InternationalSealAssignment_2");
			builder.put(grammarAccess.getAlimentaryQuestionAccess().getHealthInspectionAssignment_3(), "rule__AlimentaryQuestion__HealthInspectionAssignment_3");
			builder.put(grammarAccess.getAlimentaryQuestionAccess().getStorageConditionsAssignment_4(), "rule__AlimentaryQuestion__StorageConditionsAssignment_4");
			builder.put(grammarAccess.getValueObjectRightQuestionAccess().getNameAssignment_0(), "rule__ValueObjectRightQuestion__NameAssignment_0");
			builder.put(grammarAccess.getValueObjectRightQuestionAccess().getAnswerAssignment_2(), "rule__ValueObjectRightQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getValueObjectTokenQuestionAccess().getNameAssignment_0(), "rule__ValueObjectTokenQuestion__NameAssignment_0");
			builder.put(grammarAccess.getValueObjectTokenQuestionAccess().getAnswerAssignment_1(), "rule__ValueObjectTokenQuestion__AnswerAssignment_1");
			builder.put(grammarAccess.getValueObjectTangibleQuestionAccess().getNameAssignment_0(), "rule__ValueObjectTangibleQuestion__NameAssignment_0");
			builder.put(grammarAccess.getValueObjectTangibleQuestionAccess().getAnswerAssignment_2(), "rule__ValueObjectTangibleQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getDataRegisterAccess().getNameAssignment_1(), "rule__DataRegister__NameAssignment_1");
			builder.put(grammarAccess.getDataRegisterAccess().getTypeAssignment_3(), "rule__DataRegister__TypeAssignment_3");
			builder.put(grammarAccess.getTokenERC20Access().getNameAssignment_2(), "rule__TokenERC20__NameAssignment_2");
			builder.put(grammarAccess.getTokenERC20Access().getSymbolAssignment_4(), "rule__TokenERC20__SymbolAssignment_4");
			builder.put(grammarAccess.getTokenERC20Access().getDecimalsAssignment_6(), "rule__TokenERC20__DecimalsAssignment_6");
			builder.put(grammarAccess.getTokenERC20Access().getSupplyAssignment_8(), "rule__TokenERC20__SupplyAssignment_8");
			builder.put(grammarAccess.getTokenERC20Access().getAnswerMintSentenceAssignment_11(), "rule__TokenERC20__AnswerMintSentenceAssignment_11");
			builder.put(grammarAccess.getTokenERC20Access().getAnswerBurnSentenceAssignment_14(), "rule__TokenERC20__AnswerBurnSentenceAssignment_14");
			builder.put(grammarAccess.getTokenERC223Access().getNameAssignment_2(), "rule__TokenERC223__NameAssignment_2");
			builder.put(grammarAccess.getTokenERC223Access().getSymbolAssignment_4(), "rule__TokenERC223__SymbolAssignment_4");
			builder.put(grammarAccess.getTokenERC223Access().getDecimalsAssignment_6(), "rule__TokenERC223__DecimalsAssignment_6");
			builder.put(grammarAccess.getTokenERC223Access().getSupplyAssignment_8(), "rule__TokenERC223__SupplyAssignment_8");
			builder.put(grammarAccess.getTokenERC223Access().getAnswerMintSentenceAssignment_11(), "rule__TokenERC223__AnswerMintSentenceAssignment_11");
			builder.put(grammarAccess.getTokenERC223Access().getAnswerBurnSentenceAssignment_14(), "rule__TokenERC223__AnswerBurnSentenceAssignment_14");
			builder.put(grammarAccess.getTokenERC721Access().getNameAssignment_2(), "rule__TokenERC721__NameAssignment_2");
			builder.put(grammarAccess.getTokenERC721Access().getSymbolAssignment_4(), "rule__TokenERC721__SymbolAssignment_4");
			builder.put(grammarAccess.getTokenERC721Access().getAnswerMintSentenceAssignment_7(), "rule__TokenERC721__AnswerMintSentenceAssignment_7");
			builder.put(grammarAccess.getTokenERC721Access().getAnswerBurnSentenceAssignment_10(), "rule__TokenERC721__AnswerBurnSentenceAssignment_10");
			builder.put(grammarAccess.getTokenERC721Access().getAnswerUnitPriceAssignment_13(), "rule__TokenERC721__AnswerUnitPriceAssignment_13");
			builder.put(grammarAccess.getTokenERC721Access().getAnswerUnitCoinAssignment_14(), "rule__TokenERC721__AnswerUnitCoinAssignment_14");
			builder.put(grammarAccess.getTokenERC721Access().getAnswerMetadataSentenceAssignment_17(), "rule__TokenERC721__AnswerMetadataSentenceAssignment_17");
			builder.put(grammarAccess.getTokenERC721Access().getAnswerAssignment_18_2(), "rule__TokenERC721__AnswerAssignment_18_2");
			builder.put(grammarAccess.getTokenERC721Access().getSupplyAssignment_19_2(), "rule__TokenERC721__SupplyAssignment_19_2");
			builder.put(grammarAccess.getTimeValueExchangeDurationQuestionAccess().getNameAssignment_0(), "rule__TimeValueExchangeDurationQuestion__NameAssignment_0");
			builder.put(grammarAccess.getTimeValueExchangeDurationQuestionAccess().getAnswerAssignment_2(), "rule__TimeValueExchangeDurationQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getTimeValueExchangeDurationQuestionAccess().getAnswerUnitTimeAssignment_4(), "rule__TimeValueExchangeDurationQuestion__AnswerUnitTimeAssignment_4");
			builder.put(grammarAccess.getTimeStartValueExchangeQuestionAccess().getNameAssignment_0(), "rule__TimeStartValueExchangeQuestion__NameAssignment_0");
			builder.put(grammarAccess.getTimeStartValueExchangeQuestionAccess().getAnswerAssignment_2(), "rule__TimeStartValueExchangeQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getTimeStartValueExchangeQuestionAccess().getAnswerUnitTimeAssignment_4(), "rule__TimeStartValueExchangeQuestion__AnswerUnitTimeAssignment_4");
			builder.put(grammarAccess.getRepeatValueExchangeQuestionAccess().getNameAssignment_0(), "rule__RepeatValueExchangeQuestion__NameAssignment_0");
			builder.put(grammarAccess.getRepeatValueExchangeQuestionAccess().getAnswerAssignment_2(), "rule__RepeatValueExchangeQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getConditionsValueExchangeQuestionAccess().getNameAssignment_0(), "rule__ConditionsValueExchangeQuestion__NameAssignment_0");
			builder.put(grammarAccess.getConditionsValueExchangeQuestionAccess().getAnswerAssignment_2(), "rule__ConditionsValueExchangeQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getLegalQuestionAccess().getAgeQuestionAssignment_0(), "rule__LegalQuestion__AgeQuestionAssignment_0");
			builder.put(grammarAccess.getLegalQuestionAccess().getTaxQuestionAssignment_1(), "rule__LegalQuestion__TaxQuestionAssignment_1");
			builder.put(grammarAccess.getLegalQuestionAccess().getAdditionalLegalDocumentAssignment_2(), "rule__LegalQuestion__AdditionalLegalDocumentAssignment_2");
			builder.put(grammarAccess.getLegalQuestionAccess().getRegulatoryComplianceAssignment_3(), "rule__LegalQuestion__RegulatoryComplianceAssignment_3");
			builder.put(grammarAccess.getAgeQuestionAccess().getNameAssignment_0(), "rule__AgeQuestion__NameAssignment_0");
			builder.put(grammarAccess.getAgeQuestionAccess().getAnswerAssignment_2(), "rule__AgeQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getTaxQuestionAccess().getNameAssignment_0(), "rule__TaxQuestion__NameAssignment_0");
			builder.put(grammarAccess.getTaxQuestionAccess().getAnswerAssignment_2(), "rule__TaxQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getTaxQuestionAccess().getSubSentenceAssignment_3(), "rule__TaxQuestion__SubSentenceAssignment_3");
			builder.put(grammarAccess.getTaxQuestionAccess().getAnswerSubSentenceAssignment_5(), "rule__TaxQuestion__AnswerSubSentenceAssignment_5");
			builder.put(grammarAccess.getAdditionalLegalDocumentQuestionAccess().getNameAssignment_0(), "rule__AdditionalLegalDocumentQuestion__NameAssignment_0");
			builder.put(grammarAccess.getAdditionalLegalDocumentQuestionAccess().getAnswerAssignment_2(), "rule__AdditionalLegalDocumentQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getRegulatoryComplianceQuestionAccess().getNameAssignment_0(), "rule__RegulatoryComplianceQuestion__NameAssignment_0");
			builder.put(grammarAccess.getRegulatoryComplianceQuestionAccess().getAnswerAssignment_2(), "rule__RegulatoryComplianceQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getEconomyQuestionAccess().getMinimumAmountQuestionAssignment_0(), "rule__EconomyQuestion__MinimumAmountQuestionAssignment_0");
			builder.put(grammarAccess.getEconomyQuestionAccess().getShipmentCostResponsibilityAssignment_1(), "rule__EconomyQuestion__ShipmentCostResponsibilityAssignment_1");
			builder.put(grammarAccess.getMinimumAmountQuestionAccess().getNameAssignment_0(), "rule__MinimumAmountQuestion__NameAssignment_0");
			builder.put(grammarAccess.getMinimumAmountQuestionAccess().getAnswerAssignment_2(), "rule__MinimumAmountQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getQ1Assignment_0(), "rule__ShipmentCostResponsibilityQuestion__Q1Assignment_0");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getAnswer1Assignment_2(), "rule__ShipmentCostResponsibilityQuestion__Answer1Assignment_2");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getQ2Assignment_3_0(), "rule__ShipmentCostResponsibilityQuestion__Q2Assignment_3_0");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getAnswer2Assignment_3_2(), "rule__ShipmentCostResponsibilityQuestion__Answer2Assignment_3_2");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getAnswerUnitCoinFreightRateAssignment_3_4(), "rule__ShipmentCostResponsibilityQuestion__AnswerUnitCoinFreightRateAssignment_3_4");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getQ3Assignment_4_0(), "rule__ShipmentCostResponsibilityQuestion__Q3Assignment_4_0");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getAnswer3Assignment_4_2(), "rule__ShipmentCostResponsibilityQuestion__Answer3Assignment_4_2");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getLoadingFeeAnswerUnitCoinAssignment_4_4(), "rule__ShipmentCostResponsibilityQuestion__LoadingFeeAnswerUnitCoinAssignment_4_4");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getQ4Assignment_5_0(), "rule__ShipmentCostResponsibilityQuestion__Q4Assignment_5_0");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getAnswer4Assignment_5_2(), "rule__ShipmentCostResponsibilityQuestion__Answer4Assignment_5_2");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getUnloadingFeeAnswerUnitCoinAssignment_5_4(), "rule__ShipmentCostResponsibilityQuestion__UnloadingFeeAnswerUnitCoinAssignment_5_4");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getQ5Assignment_6_0(), "rule__ShipmentCostResponsibilityQuestion__Q5Assignment_6_0");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getAnswer5Assignment_6_2(), "rule__ShipmentCostResponsibilityQuestion__Answer5Assignment_6_2");
			builder.put(grammarAccess.getShipmentCostResponsibilityQuestionAccess().getTransportRateAnswerUnitCoinAssignment_6_4(), "rule__ShipmentCostResponsibilityQuestion__TransportRateAnswerUnitCoinAssignment_6_4");
			builder.put(grammarAccess.getShipmentDetailsQuestionAccess().getNameAssignment_0(), "rule__ShipmentDetailsQuestion__NameAssignment_0");
			builder.put(grammarAccess.getShipmentDetailsQuestionAccess().getAnswerAssignment_2(), "rule__ShipmentDetailsQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getSanitaryControlQuestionAccess().getNameAssignment_0(), "rule__SanitaryControlQuestion__NameAssignment_0");
			builder.put(grammarAccess.getSanitaryControlQuestionAccess().getAnswerAssignment_2(), "rule__SanitaryControlQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getCustomsQuestionAccess().getNameAssignment_0(), "rule__CustomsQuestion__NameAssignment_0");
			builder.put(grammarAccess.getCustomsQuestionAccess().getAnswerAssignment_2(), "rule__CustomsQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getImportTaxQuestionAccess().getNameAssignment_0(), "rule__ImportTaxQuestion__NameAssignment_0");
			builder.put(grammarAccess.getImportTaxQuestionAccess().getAnswerAssignment_2(), "rule__ImportTaxQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getImportTaxQuestionAccess().getSubSentenceAssignment_3(), "rule__ImportTaxQuestion__SubSentenceAssignment_3");
			builder.put(grammarAccess.getTaxShipmentDetailsQuestionAccess().getNameAssignment_0(), "rule__TaxShipmentDetailsQuestion__NameAssignment_0");
			builder.put(grammarAccess.getTaxShipmentDetailsQuestionAccess().getAnswerAssignment_2(), "rule__TaxShipmentDetailsQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getTaxShipmentDetailsQuestionAccess().getAnswerUnitCoinAssignment_3(), "rule__TaxShipmentDetailsQuestion__AnswerUnitCoinAssignment_3");
			builder.put(grammarAccess.getGeographicalQuestionAccess().getNameAssignment_0(), "rule__GeographicalQuestion__NameAssignment_0");
			builder.put(grammarAccess.getGeographicalQuestionAccess().getAnswerAssignment_2(), "rule__GeographicalQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getGeographicalQuestionAccess().getSubSentenceRestrictionAssignment_3(), "rule__GeographicalQuestion__SubSentenceRestrictionAssignment_3");
			builder.put(grammarAccess.getGeographicalRestrictionQuestionAccess().getNameAssignment_0(), "rule__GeographicalRestrictionQuestion__NameAssignment_0");
			builder.put(grammarAccess.getGeographicalRestrictionQuestionAccess().getAnswerAssignment_2(), "rule__GeographicalRestrictionQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getAddressPickupQuestionAccess().getNameAssignment_0(), "rule__AddressPickupQuestion__NameAssignment_0");
			builder.put(grammarAccess.getAddressPickupQuestionAccess().getAnswerAssignment_2(), "rule__AddressPickupQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getAddressDeliveryQuestionAccess().getNameAssignment_0(), "rule__AddressDeliveryQuestion__NameAssignment_0");
			builder.put(grammarAccess.getAddressDeliveryQuestionAccess().getAnswerAssignment_2(), "rule__AddressDeliveryQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getShipmentTrackingNumberQuestionAccess().getNameAssignment_0(), "rule__ShipmentTrackingNumberQuestion__NameAssignment_0");
			builder.put(grammarAccess.getShipmentTrackingNumberQuestionAccess().getAnswerAssignment_2(), "rule__ShipmentTrackingNumberQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getDangerousLoadQuestionAccess().getNameAssignment_0(), "rule__DangerousLoadQuestion__NameAssignment_0");
			builder.put(grammarAccess.getDangerousLoadQuestionAccess().getAnswerAssignment_2(), "rule__DangerousLoadQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getDangerousLoadQuestionAccess().getSubSentenceSpecialMeasuresAssignment_3(), "rule__DangerousLoadQuestion__SubSentenceSpecialMeasuresAssignment_3");
			builder.put(grammarAccess.getSpecialMeasuresQuestionAccess().getNameAssignment_0(), "rule__SpecialMeasuresQuestion__NameAssignment_0");
			builder.put(grammarAccess.getSpecialMeasuresQuestionAccess().getAnswerAssignment_2(), "rule__SpecialMeasuresQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getPerishableQuestionAccess().getNameAssignment_0(), "rule__PerishableQuestion__NameAssignment_0");
			builder.put(grammarAccess.getPerishableQuestionAccess().getAnswerAssignment_2(), "rule__PerishableQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getPerishableQuestionAccess().getSubSentencePerishableAssignment_3(), "rule__PerishableQuestion__SubSentencePerishableAssignment_3");
			builder.put(grammarAccess.getExpirationDateQuestionAccess().getNameAssignment_0(), "rule__ExpirationDateQuestion__NameAssignment_0");
			builder.put(grammarAccess.getExpirationDateQuestionAccess().getAnswerAssignment_2(), "rule__ExpirationDateQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getCargoTypeQuestionAccess().getNameAssignment_0(), "rule__CargoTypeQuestion__NameAssignment_0");
			builder.put(grammarAccess.getCargoTypeQuestionAccess().getAnswerAssignment_2(), "rule__CargoTypeQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getCargoWeightQuestionAccess().getNameAssignment_0(), "rule__CargoWeightQuestion__NameAssignment_0");
			builder.put(grammarAccess.getCargoWeightQuestionAccess().getAnswerAssignment_2(), "rule__CargoWeightQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getCargoDimensionsQuestionAccess().getNameAssignment_0(), "rule__CargoDimensionsQuestion__NameAssignment_0");
			builder.put(grammarAccess.getCargoDimensionsQuestionAccess().getLengthAssignment_2(), "rule__CargoDimensionsQuestion__LengthAssignment_2");
			builder.put(grammarAccess.getCargoDimensionsQuestionAccess().getWidthAssignment_4(), "rule__CargoDimensionsQuestion__WidthAssignment_4");
			builder.put(grammarAccess.getCargoDimensionsQuestionAccess().getDepthAssignment_6(), "rule__CargoDimensionsQuestion__DepthAssignment_6");
			builder.put(grammarAccess.getSeaShipmentQuestionAccess().getNameAssignment_0(), "rule__SeaShipmentQuestion__NameAssignment_0");
			builder.put(grammarAccess.getSeaShipmentQuestionAccess().getAnswerAssignment_2(), "rule__SeaShipmentQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getSeaShipmentQuestionAccess().getMaritimeAssignment_3(), "rule__SeaShipmentQuestion__MaritimeAssignment_3");
			builder.put(grammarAccess.getMaritimeQuestionAccess().getQ1Assignment_0(), "rule__MaritimeQuestion__Q1Assignment_0");
			builder.put(grammarAccess.getMaritimeQuestionAccess().getAnswer1Assignment_2(), "rule__MaritimeQuestion__Answer1Assignment_2");
			builder.put(grammarAccess.getMaritimeQuestionAccess().getQ2Assignment_3(), "rule__MaritimeQuestion__Q2Assignment_3");
			builder.put(grammarAccess.getMaritimeQuestionAccess().getAnswer2Assignment_5(), "rule__MaritimeQuestion__Answer2Assignment_5");
			builder.put(grammarAccess.getMaritimeQuestionAccess().getQ3Assignment_6_0(), "rule__MaritimeQuestion__Q3Assignment_6_0");
			builder.put(grammarAccess.getMaritimeQuestionAccess().getAnswer3Assignment_6_2(), "rule__MaritimeQuestion__Answer3Assignment_6_2");
			builder.put(grammarAccess.getMaritimeQuestionAccess().getQ4Assignment_7(), "rule__MaritimeQuestion__Q4Assignment_7");
			builder.put(grammarAccess.getMaritimeQuestionAccess().getAnswer4Assignment_9(), "rule__MaritimeQuestion__Answer4Assignment_9");
			builder.put(grammarAccess.getMaritimeQuestionAccess().getSubSentenceAssignment_10(), "rule__MaritimeQuestion__SubSentenceAssignment_10");
			builder.put(grammarAccess.getVoyageQuestionAccess().getNameAssignment_0(), "rule__VoyageQuestion__NameAssignment_0");
			builder.put(grammarAccess.getVoyageQuestionAccess().getAnswerSubSentenceAssignment_2(), "rule__VoyageQuestion__AnswerSubSentenceAssignment_2");
			builder.put(grammarAccess.getVoyageQuestionAccess().getAnswerUnitTimeAssignment_4(), "rule__VoyageQuestion__AnswerUnitTimeAssignment_4");
			builder.put(grammarAccess.getMeansTransportQuestionAccess().getNameAssignment_0(), "rule__MeansTransportQuestion__NameAssignment_0");
			builder.put(grammarAccess.getMeansTransportQuestionAccess().getAnswerAssignment_2(), "rule__MeansTransportQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getCompanyQuestionAccess().getNameAssignment_0(), "rule__CompanyQuestion__NameAssignment_0");
			builder.put(grammarAccess.getCompanyQuestionAccess().getAnswerAssignment_2(), "rule__CompanyQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getDeliveryDeadlineQuestionAccess().getNameAssignment_0(), "rule__DeliveryDeadlineQuestion__NameAssignment_0");
			builder.put(grammarAccess.getDeliveryDeadlineQuestionAccess().getAnswerAssignment_2(), "rule__DeliveryDeadlineQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getUpdatesAndMonitoringQuestionAccess().getNameAssignment_0(), "rule__UpdatesAndMonitoringQuestion__NameAssignment_0");
			builder.put(grammarAccess.getUpdatesAndMonitoringQuestionAccess().getAnswerAssignment_2(), "rule__UpdatesAndMonitoringQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getExternalMediatorQuestionAccess().getNameAssignment_0(), "rule__ExternalMediatorQuestion__NameAssignment_0");
			builder.put(grammarAccess.getExternalMediatorQuestionAccess().getAnswerAssignment_2(), "rule__ExternalMediatorQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getExternalMediatorQuestionAccess().getSubsentenceAssignment_3(), "rule__ExternalMediatorQuestion__SubsentenceAssignment_3");
			builder.put(grammarAccess.getMediatorNameQuestionAccess().getNameAssignment_0(), "rule__MediatorNameQuestion__NameAssignment_0");
			builder.put(grammarAccess.getMediatorNameQuestionAccess().getAnswerAssignment_2(), "rule__MediatorNameQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getShipmentInsuranceQuestionAccess().getNameAssignment_0(), "rule__ShipmentInsuranceQuestion__NameAssignment_0");
			builder.put(grammarAccess.getShipmentInsuranceQuestionAccess().getAnswerAssignment_2(), "rule__ShipmentInsuranceQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getInsuranceDetailsQuestionAccess().getQ1Assignment_0_0(), "rule__InsuranceDetailsQuestion__Q1Assignment_0_0");
			builder.put(grammarAccess.getInsuranceDetailsQuestionAccess().getAnswer1Assignment_0_2(), "rule__InsuranceDetailsQuestion__Answer1Assignment_0_2");
			builder.put(grammarAccess.getInsuranceDetailsQuestionAccess().getAnswerUnitCoin1Assignment_0_4(), "rule__InsuranceDetailsQuestion__AnswerUnitCoin1Assignment_0_4");
			builder.put(grammarAccess.getInsuranceDetailsQuestionAccess().getQ2Assignment_1_0(), "rule__InsuranceDetailsQuestion__Q2Assignment_1_0");
			builder.put(grammarAccess.getInsuranceDetailsQuestionAccess().getAnswer2Assignment_1_2(), "rule__InsuranceDetailsQuestion__Answer2Assignment_1_2");
			builder.put(grammarAccess.getInsuranceDetailsQuestionAccess().getQ3Assignment_2_0(), "rule__InsuranceDetailsQuestion__Q3Assignment_2_0");
			builder.put(grammarAccess.getInsuranceDetailsQuestionAccess().getAnswer3Assignment_2_2(), "rule__InsuranceDetailsQuestion__Answer3Assignment_2_2");
			builder.put(grammarAccess.getInsuranceDetailsQuestionAccess().getAnswerUnitCoin3Assignment_2_4(), "rule__InsuranceDetailsQuestion__AnswerUnitCoin3Assignment_2_4");
			builder.put(grammarAccess.getReturnsOrCancellationsQuestionAccess().getNameAssignment_0(), "rule__ReturnsOrCancellationsQuestion__NameAssignment_0");
			builder.put(grammarAccess.getReturnsOrCancellationsQuestionAccess().getAnswerAssignment_2(), "rule__ReturnsOrCancellationsQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getReturnsOrCancellationsQuestionAccess().getSubsentenceAssignment_3(), "rule__ReturnsOrCancellationsQuestion__SubsentenceAssignment_3");
			builder.put(grammarAccess.getReturnsManagementQuestionAccess().getNameAssignment_0(), "rule__ReturnsManagementQuestion__NameAssignment_0");
			builder.put(grammarAccess.getReturnsManagementQuestionAccess().getAnswerAssignment_2(), "rule__ReturnsManagementQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getPenaltyForNeglectQuestionAccess().getNameAssignment_0(), "rule__PenaltyForNeglectQuestion__NameAssignment_0");
			builder.put(grammarAccess.getPenaltyForNeglectQuestionAccess().getAnswerAssignment_2(), "rule__PenaltyForNeglectQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getAgreedPriceQuestionAccess().getNameAssignment_0(), "rule__AgreedPriceQuestion__NameAssignment_0");
			builder.put(grammarAccess.getAgreedPriceQuestionAccess().getAnswerAssignment_2(), "rule__AgreedPriceQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getAgreedPriceQuestionAccess().getAnswerUnitCoinAssignment_4(), "rule__AgreedPriceQuestion__AnswerUnitCoinAssignment_4");
			builder.put(grammarAccess.getProductQualityQuestionAccess().getNameAssignment_0(), "rule__ProductQualityQuestion__NameAssignment_0");
			builder.put(grammarAccess.getProductQualityQuestionAccess().getAnswerAssignment_2(), "rule__ProductQualityQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getProductQualityQuestionAccess().getExpectedQualityAssignment_3(), "rule__ProductQualityQuestion__ExpectedQualityAssignment_3");
			builder.put(grammarAccess.getExpectedQualityQuestionAccess().getQ1Assignment_0(), "rule__ExpectedQualityQuestion__Q1Assignment_0");
			builder.put(grammarAccess.getExpectedQualityQuestionAccess().getAnswer1Assignment_2(), "rule__ExpectedQualityQuestion__Answer1Assignment_2");
			builder.put(grammarAccess.getExpectedQualityQuestionAccess().getQ2Assignment_3(), "rule__ExpectedQualityQuestion__Q2Assignment_3");
			builder.put(grammarAccess.getExpectedQualityQuestionAccess().getAnswer2Assignment_5(), "rule__ExpectedQualityQuestion__Answer2Assignment_5");
			builder.put(grammarAccess.getInternationalSealQuestionAccess().getNameAssignment_0(), "rule__InternationalSealQuestion__NameAssignment_0");
			builder.put(grammarAccess.getInternationalSealQuestionAccess().getAnswerAssignment_2(), "rule__InternationalSealQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getInternationalSealQuestionAccess().getSubsentenceAssignment_3(), "rule__InternationalSealQuestion__SubsentenceAssignment_3");
			builder.put(grammarAccess.getInternacionalSealNameQuestionAccess().getNameAssignment_0(), "rule__InternacionalSealNameQuestion__NameAssignment_0");
			builder.put(grammarAccess.getInternacionalSealNameQuestionAccess().getAnswerAssignment_2(), "rule__InternacionalSealNameQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getHealthInspectionQuestionAccess().getNameAssignment_0(), "rule__HealthInspectionQuestion__NameAssignment_0");
			builder.put(grammarAccess.getHealthInspectionQuestionAccess().getAnswerAssignment_2(), "rule__HealthInspectionQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getHealthInspectionQuestionAccess().getSubsentenceAssignment_3(), "rule__HealthInspectionQuestion__SubsentenceAssignment_3");
			builder.put(grammarAccess.getInspectionResultQuestionAccess().getNameAssignment_0(), "rule__InspectionResultQuestion__NameAssignment_0");
			builder.put(grammarAccess.getInspectionResultQuestionAccess().getAnswerAssignment_2(), "rule__InspectionResultQuestion__AnswerAssignment_2");
			builder.put(grammarAccess.getStorageConditionsQuestionAccess().getNameAssignment_0(), "rule__StorageConditionsQuestion__NameAssignment_0");
			builder.put(grammarAccess.getStorageConditionsQuestionAccess().getAnswerAssignment_2(), "rule__StorageConditionsQuestion__AnswerAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private SmaCQAGrammarAccess grammarAccess;

	@Override
	protected InternalSmaCQAParser createParser() {
		InternalSmaCQAParser result = new InternalSmaCQAParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SmaCQAGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SmaCQAGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
