/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.smaCQA.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.xtext.smaCQA.DangerousLoadQuestion;
import org.xtext.smaCQA.SmaCQAFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Dangerous Load Question</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class DangerousLoadQuestionTest extends TestCase {

	/**
	 * The fixture for this Dangerous Load Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DangerousLoadQuestion fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(DangerousLoadQuestionTest.class);
	}

	/**
	 * Constructs a new Dangerous Load Question test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DangerousLoadQuestionTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Dangerous Load Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(DangerousLoadQuestion fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Dangerous Load Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DangerousLoadQuestion getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SmaCQAFactory.eINSTANCE.createDangerousLoadQuestion());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //DangerousLoadQuestionTest
