/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.smaCQA.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.xtext.smaCQA.GeographicalRestrictionQuestion;
import org.xtext.smaCQA.SmaCQAFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Geographical Restriction Question</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class GeographicalRestrictionQuestionTest extends TestCase {

	/**
	 * The fixture for this Geographical Restriction Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GeographicalRestrictionQuestion fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(GeographicalRestrictionQuestionTest.class);
	}

	/**
	 * Constructs a new Geographical Restriction Question test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public GeographicalRestrictionQuestionTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Geographical Restriction Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(GeographicalRestrictionQuestion fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Geographical Restriction Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GeographicalRestrictionQuestion getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SmaCQAFactory.eINSTANCE.createGeographicalRestrictionQuestion());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //GeographicalRestrictionQuestionTest
