/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.smaCQA.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.xtext.smaCQA.MeansTransportQuestion;
import org.xtext.smaCQA.SmaCQAFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Means Transport Question</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class MeansTransportQuestionTest extends TestCase {

	/**
	 * The fixture for this Means Transport Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeansTransportQuestion fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(MeansTransportQuestionTest.class);
	}

	/**
	 * Constructs a new Means Transport Question test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public MeansTransportQuestionTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Means Transport Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(MeansTransportQuestion fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Means Transport Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeansTransportQuestion getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SmaCQAFactory.eINSTANCE.createMeansTransportQuestion());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //MeansTransportQuestionTest
