/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.smaCQA.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.xtext.smaCQA.SeaShipmentQuestion;
import org.xtext.smaCQA.SmaCQAFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Sea Shipment Question</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class SeaShipmentQuestionTest extends TestCase {

	/**
	 * The fixture for this Sea Shipment Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SeaShipmentQuestion fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(SeaShipmentQuestionTest.class);
	}

	/**
	 * Constructs a new Sea Shipment Question test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SeaShipmentQuestionTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Sea Shipment Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(SeaShipmentQuestion fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Sea Shipment Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SeaShipmentQuestion getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SmaCQAFactory.eINSTANCE.createSeaShipmentQuestion());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //SeaShipmentQuestionTest
