/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.smaCQA.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.xtext.smaCQA.SmaCQAFactory;
import org.xtext.smaCQA.SpecialMeasuresQuestion;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Special Measures Question</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class SpecialMeasuresQuestionTest extends TestCase {

	/**
	 * The fixture for this Special Measures Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecialMeasuresQuestion fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(SpecialMeasuresQuestionTest.class);
	}

	/**
	 * Constructs a new Special Measures Question test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SpecialMeasuresQuestionTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Special Measures Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(SpecialMeasuresQuestion fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Special Measures Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecialMeasuresQuestion getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SmaCQAFactory.eINSTANCE.createSpecialMeasuresQuestion());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //SpecialMeasuresQuestionTest
