/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.smaCQA.tests;

import junit.textui.TestRunner;

import org.xtext.smaCQA.SmaCQAFactory;
import org.xtext.smaCQA.TokenERC20;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Token ERC20</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class TokenERC20Test extends TokenTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(TokenERC20Test.class);
	}

	/**
	 * Constructs a new Token ERC20 test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public TokenERC20Test(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Token ERC20 test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected TokenERC20 getFixture() {
		return (TokenERC20)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SmaCQAFactory.eINSTANCE.createTokenERC20());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //TokenERC20Test
