/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.smaCQA.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.xtext.smaCQA.SmaCQAFactory;
import org.xtext.smaCQA.ValueObjectQuestion;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Value Object Question</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class ValueObjectQuestionTest extends TestCase {

	/**
	 * The fixture for this Value Object Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ValueObjectQuestion fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(ValueObjectQuestionTest.class);
	}

	/**
	 * Constructs a new Value Object Question test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ValueObjectQuestionTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Value Object Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(ValueObjectQuestion fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Value Object Question test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ValueObjectQuestion getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SmaCQAFactory.eINSTANCE.createValueObjectQuestion());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //ValueObjectQuestionTest
